backend/controllers/IssuePointAdminController.php
<?php

namespace backend\controllers;

use backend\models\form\ConfirmOrderForm;
use backend\models\form\ApproveOrderForm;
use common\models\IssuePoint;
use common\models\Order;
use common\models\search\OrderSearch;
use Yii;
use common\models\Device;
use common\models\search\DeviceSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * IssuePointAdminController
 */
class IssuePointAdminController extends Controller
{
    /**
     * Index models.
     * @return mixed
     */
    public function actionIndex()
    {
        $IssuePointDetail = IssuePoint::getIssuePointDetailByAdmin(Yii::$app->user->id);

        return $this->render('index', [
            'IssuePointDetail' => $IssuePointDetail,
        ]);
    }

    /**
     * Lists all Device models.
     * @return mixed
     */
    public function actionDevices()
    {
        $searchModel = new DeviceSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,  IssuePoint::getIssuePointByAdmin(Yii::$app->user->id));

        return $this->render('devices', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Device model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDeviceView($id)
    {
        return $this->render('device-view', [
            'model' => $this->findDeviceModel($id),
        ]);
    }

    /**
     * Updates an existing Device model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDeviceUpdate($id)
    {
        $model = $this->findDeviceModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['device-view', 'id' => $model->id]);
        }

        return $this->render('device-update', [
            'model' => $model,
        ]);
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionOrders()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,  IssuePoint::getIssuePointByAdmin(Yii::$app->user->id));

        return $this->render('orders', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionOrderView($id)
    {
        return $this->render('order-view', [
            'model' => $this->findOrderModel($id),
        ]);
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionOrderUpdate($id)
    {
        $model = $this->findOrderModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['order-view', 'id' => $model->id]);
        }

        return $this->render('order-update', [
            'model' => $model,
        ]);
    }

    /**
     * Index models.
     * @return mixed
     */
    public function actionConfirmOrder()
    {
        $modelForm = new ConfirmOrderForm();

        if ($modelForm->load(Yii::$app->request->post()) && $modelForm->validate()) {
            return $this->redirect(['order-view', 'id' => $modelForm->confirm()]);
        } else {
            return $this->render('confirm-order', [
                'modelForm' => $modelForm,
            ]);
        }

    }

    /**
     * Index models.
     * @return mixed
     */
    public function actionApproveOrder()
    {
        $modelForm = new ApproveOrderForm();
        $modelForm->scooter_state = Order::SCOOTER_STATE_OK;

        if ($modelForm->load(Yii::$app->request->post()) && $modelForm->validate()) {
            return $this->redirect(['order-view', 'id' => $modelForm->approve()]);
        } else {
            return $this->render('approve-order', [
                'modelForm' => $modelForm,
            ]);
        }

    }

    /**
     * Finds the Device model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Device the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findDeviceModel($id)
    {
        if (($model = Device::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findOrderModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/layouts/admin-menu.php
<?php

use common\widgets\IconMenu;

echo IconMenu::widget([
    'options' => ['class' => 'main-nav', 'id' => 'main-nav'],
    'items' => [
        ['label' => 'Меню', 'options' => ['class' => 'main-nav-label']],
        ['label' => 'Рабочий стол', 'icon' => 'monitor', 'url' => ['/'], 'visible' => Yii::$app->user->can('admin')],
        [
            'label' => 'Записи',
            'icon' => 'book-open',
            'url' => [''],
            'items' => [
                ['label' => 'Тип записей', 'url' => ['/article/articles-type-crud/']],
                ['label' => 'Записи', 'url' => ['/article/article-crud/']],
            ],
            'visible' => Yii::$app->user->can('admin')
        ],
        ['label' => 'FAQ', 'icon' => 'forum', 'url' => ['/faq/crud'], 'visible' => Yii::$app->user->can('admin')],
        ['label' => 'Точки выдачи', 'icon' => 'map-marker', 'url' => ['/issue-point'], 'visible' => Yii::$app->user->can('admin')],
        [
            'label' => 'Устройства',
            'icon' => 'bike',
            'url' => [''],
            'items' => [
                ['label' => 'Тип устройства', 'url' => ['/device-type']],
                ['label' => 'Устройства', 'url' => ['/device']],
            ],
            'visible' => Yii::$app->user->can('admin')
        ],
        ['label' => 'Тарифы', 'icon' => 'currency-usd', 'url' => ['/tariff'], 'visible' => Yii::$app->user->can('admin')],
        ['label' => 'Заказы', 'icon' => 'view-list', 'url' => ['/order'], 'visible' => Yii::$app->user->can('admin')],
        ['label' => 'Профили пользователей', 'icon' => 'account', 'url' => ['/userprofile/user-profile-crud'], 'visible' => Yii::$app->user->can('admin')],
    ]
]);

backend/views/layouts/content.php
<?php
/* @var $content string */

use common\widgets\Alert;

?>

<div class="page">
    <header class="ribbon">
        <h2>
            <?=  $this->title; ?>
        </h2>
    </header>
    <div class="page-content">
        <div class="container-fluid">
            <?= Alert::widget() ?>
            <?= $content ?>
        </div>
    </div>
</div>

backend/views/layouts/header.php
<nav class="navbar navbar-blue navbar-fixed-top topbar" style="" id="topbar">

    <div class="navbar-header navbar-always-float navbar-left">
        <button class="btn btn-transparent-light navbar-btn navbar-sidebar-toggle  hidden-xs ">
            <i class="mdi mdi-menu"></i>
        </button>
        <button class="btn btn-transparent-light navbar-btn navbar-sidebar-collapse hidden-sm hidden-md hidden-lg">
            <i class="mdi mdi-menu"></i>
        </button>
        <a class="navbar-brand" href="<?= Yii::$app->homeUrl ?>">
            <i class="mdi mdi-cellphone-iphone"></i><span class="navbar-brand-text">Scooters</span>
        </a>
    </div>

</nav>

backend/views/layouts/issue-point-admin-menu.php
<?php

use common\widgets\IconMenu;

echo IconMenu::widget([
    'options' => ['class' => 'main-nav', 'id' => 'main-nav'],
    'items' => [
        ['label' => 'Меню', 'options' => ['class' => 'main-nav-label']],
        ['label' => 'Точка выдачи', 'icon' => 'map-marker', 'url' => ['/issue-point-admin']],
        ['label' => 'Устройства', 'icon' => 'bike', 'url' => ['/issue-point-admin/devices']],
        ['label' => 'Заказы', 'icon' => 'view-list', 'url' => ['/issue-point-admin/orders']],
        ['label' => 'Новый заказ', 'icon' => 'arrow-up', 'url' => ['/issue-point-admin/confirm-order']],
        ['label' => 'Закончить заказ', 'icon' => 'arrow-down', 'url' => ['/issue-point-admin/approve-order']],
    ]
]);

backend/views/layouts/loader.php
<div id="loader-container" style="display:none">
    <div id="loader">
        <div class="loader-inner line-scale">
            <div></div><div></div><div></div><div></div><div></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var loadersign = document.getElementById('loader-container');
    loadersign.style.display = "block";
    window.onload = function() {
        loadersign.style.display = "none";
    }
</script>

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use backend\assets\AdminThemeAsset;

AppAsset::register($this);
AdminThemeAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <style>
        #loader-container {
            display: block;
            position: fixed;
            z-index: 100;
            left: 0;
            top:0;
            width: 100%;
            height: 100%;
            width: 100vw;
            height: 100vh;
            background: rgb(241,246,251);
            overflow: hidden;
        }
        #loader-container .loader-inner {
            text-align: center;
            position: absolute;
            top:40%;
            left:0;
            width: 100%;
            top:40vh;
            left:0;
            width: 100vw;
            transform: scale(1);

        }
        #loader-container .loader-inner div {
            background-color: #7359EE;
        }
    </style>
</head>
<body>
<?php $this->beginBody() ?>

<div class="page-wrapper fixed-navbar-top">

    <?= $this->render(
        'loader.php'
    ) ?>

    <?= $this->render(
        'header.php'
    ) ?>

    <?= $this->render(
        'sidebar.php'
    ) ?>

    <?= $this->render(
        'content.php',
        ['content' => $content]
    ) ?>

</div>



<?php $this->endBody() ?>
<script>
    $(function(){
        $('.datatable').DataTable()
    });
</script>
</body>

</html>
<?php $this->endPage() ?>

backend/views/layouts/sidebar.php
<?php

use common\widgets\IconMenu;
use yii\helpers\Html;
?>
<div class="sidebar sidebar-left sidebar-dark sidebar-fixed sidebar-navbar-theme" id="sidebar">

    <div class="sidebar-scrollable-content">

        <div class="sidebar-body">

            <div class="sidebar-cover">
                <div class="sidebar-user">
                    <div class="sidebar-user-img">
                        <img src="/backend/web/img/user-avatar.png" alt="" class="img-circle img-online img-thumbnailimg-thumbnail-primary">
                    </div>
                    <div class="sidebar-user-name">
                        <?= Yii::$app->user->identity->userProfile->name . ' ' . Yii::$app->user->identity->userProfile->surname?>
                        <span class="text-small sidebar-user-email"><?= Yii::$app->user->identity->login?></span>
                    </div>
                </div>
            </div>

            <div class="main-menu-container">

                <?php if (Yii::$app->user->can('admin')) {
                    echo $this->render('admin-menu');
                } elseif (Yii::$app->user->can('issue_point_admin')) {
                    echo $this->render('issue-point-admin-menu');
                }?>



            </div>

        </div>

    </div>

    <div class="sidebar-footer">
        <div class="horizontal-nav">



            <ul class="horizontal-nav horizontal-nav-3">
                <li>
                    <a href=""><i class="mdi mdi-settings"></i></a>
                </li>
                <li>
                    <a href=""><i class="mdi mdi-account"></i></a>
                </li>
                <li>
                    <?php echo Html::beginForm(['/user/default/logout'], 'post')
                    . Html::submitButton(
                        '<i class="mdi mdi-logout"></i>',
                        ['class' => '']
                    )
                    . Html::endForm() ?>
                </li>
            </ul>
        </div>
    </div>

</div>